name: Pause CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.3.0'

      - name: Install dependencies
        run: npm install

      - name: Test eslint and prettier
        run: npm run cleanup
